apiVersion: v1
kind: Pod
metadata:
  name: lab7pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: lab7pvc
  containers:
    - name: task-pv-container
      image: busybox
      args:
        - sleep
        - infinity
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage