apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab7pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/storage"
