apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scaledapp
  name: scaledapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scaledapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scaledapp
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
