apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: upapp
  name: upapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: upapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: upapp
    spec:
      containers:
      - image: nginx:1.17
        name: nginx
        resources: {}
status: {}
